
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\tModLoader.targets" />
  <PropertyGroup>
    <AssemblyName>MagicStorage</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);NETPLAY</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'" />
  <ItemGroup>
    <EmbeddedResource Include="Common\Systems\scramble" />
    <EmbeddedResource Include="Common\Systems\unscramble" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="SerousCommonLib">
      <HintPath>..\references\1.4.4\SerousCommonLib.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>